Repository WildAid/o-fish-ios, pull requests merged in 2020-09, with the labels that each got.

#207 Prefill crew from most recent boarding
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  O-FISHTests/AttachmentsViewModelTests.swift
  O-FISHTests/CrewMemberViewModelTests.swift
  Podfile.lock
  o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
  o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
  o-fish-ios/Views/Components/BoardVesselButton.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
  o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
Labels: enhancement

#205 Input field for "Reason for Red"
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  Podfile.lock
  o-fish-ios/ViewModel/Report/SafetyLevelViewModel.swift
  o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
Labels: enhancement

#227 Prefill attachments for vessel
  o-fish-ios/Views/Components/BoardVesselButton.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
  o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
Labels: enhancement

#214 Remove realm connection; begin moving views over to fluid model
  o-fish-ios/Helpers/Date.swift
  o-fish-ios/Helpers/RealmConnection.swift
  o-fish-ios/Model/Settings.swift
  o-fish-ios/SceneDelegate.swift
  o-fish-ios/ViewModel/Report/PhotoViewModel.swift
  o-fish-ios/ViewModel/Report/ReportViewModel.swift
  o-fish-ios/ViewModel/User/DutyChangeViewModel.swift
  o-fish-ios/Views/Components/Pictures/PhotoIDsDisplayView.swift
  o-fish-ios/Views/LoginView.swift
  o-fish-ios/Views/MainNavigationRootView.swift
  o-fish-ios/Views/PatrolBoat/DutyState.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/LoadingVesselRecordView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/PhotoQueryManager.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: Architecture

#243 Risks on Boarding Reports
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios.xcodeproj/xcshareddata/xcschemes/o-fish-ios.xcscheme
  o-fish-ios/ViewModel/Report/SampleReportViewModel.swift
  o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
  o-fish-ios/Views/ReportDetails/RiskSummaryView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
  o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
Labels: bug

#252 Add accessible fonts it is on design
  o-fish-ios/Views/Components/ButtonField.swift
  o-fish-ios/Views/Components/CaptionLabel.swift
  o-fish-ios/Views/Components/ColumnText.swift
  o-fish-ios/Views/Components/Icons/IconLabel.swift
  o-fish-ios/Views/Components/InputField.swift
  o-fish-ios/Views/Components/LabeledDoubleOutput.swift
  o-fish-ios/Views/Components/LabeledText.swift
  o-fish-ios/Views/Components/LabeledTextInput.swift
  o-fish-ios/Views/Components/MultilineTextView.swift
  o-fish-ios/Views/Components/Picker/Business/BusinessPickerDataView.swift
  o-fish-ios/Views/Components/Picker/Country/CountryPickerDataView.swift
  o-fish-ios/Views/Components/Picker/SearchBarView.swift
  o-fish-ios/Views/Components/Picker/TextPickerView.swift
  o-fish-ios/Views/Components/Picker/Violation/ViolationPickerDataView.swift
  o-fish-ios/Views/LoginView.swift
  o-fish-ios/Views/PatrolBoat/ColoredToggleStyle.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
  o-fish-ios/Views/PatrolBoat/SearchBarButton.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/EmptyStateView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordItemView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
  o-fish-ios/Views/ReportDetails/DateTimeStackView.swift
  o-fish-ios/Views/ReportDetails/StatusSymbolView.swift
  o-fish-ios/Views/ReportFlow/CrewMemberShortView.swift
Labels: enhancement

#254 Location reset when moving back to basic info view
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
Labels: bug

#230 Add cancel button to pickers view
  o-fish-ios/Views/Components/Picker/SearchableView.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseCrewMemberView.swift
Labels: enhancement

#255 Syncuser realm access
  o-fish-ios/Model/Settings.swift
  o-fish-ios/Views/LoginView.swift
  o-fish-ios/Views/MainNavigationRootView.swift
  o-fish-ios/Views/PatrolBoat/DutyState.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/LoadingVesselRecordView.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: Architecture

#258 On login view, show progress view until everything has completed
  o-fish-ios/Views/LoginView.swift
Labels: enhancement

#262 `menuData` shouldn't be `@Published` or it creates a loop
  o-fish-ios/Model/Settings.swift
Labels: bug

#276 Make weight and count in Catch easier to work with
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/ViewModel/Report/CatchViewModel.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchView.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseQuantityTypeView.swift
Labels: enhancement

#275 Profile find records in the same line
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Assets.xcassets/vesselButton.imageset/Contents.json
  o-fish-ios/Assets.xcassets/vesselButton.imageset/vesselButton.pdf
  o-fish-ios/Assets.xcassets/vesselIconButton.imageset/vesselIconButton.pdf
  o-fish-ios/Design/Color+Design.swift
  o-fish-ios/ViewModel/User/SampleUserViewModel.swift
  o-fish-ios/Views/Components/OnOffCircleView.swift
  o-fish-ios/Views/Components/PatrolBoatView/BoardVesselButtonView.swift
  o-fish-ios/Views/Components/PatrolBoatView/BottomPatrolView.swift
  o-fish-ios/Views/Components/PatrolBoatView/DraftBoardingsButtonView.swift
  o-fish-ios/Views/Components/PatrolBoatView/FindRecordsButtonView.swift
  o-fish-ios/Views/PatrolBoat/BoardButton.swift
  o-fish-ios/Views/PatrolBoat/ColoredToggleStyle.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
  o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
  o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
  o-fish-ios/Views/PatrolBoat/TextToggle.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordItemView.swift
  o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: enhancement

#284 Add `draft` optional Bool to Reports
  o-fish-ios/Model/Report/Report.swift
  o-fish-ios/ViewModel/Report/DeliveryViewModel.swift
  o-fish-ios/ViewModel/Report/PhotoViewModel.swift
  o-fish-ios/ViewModel/Report/ReportViewModel.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: enhancement

#283 Clear loading screen if login fails
  o-fish-ios/Views/LoginView.swift
Labels: bug

#288 Make model and view-model mutable
  o-fish-ios/Model/Report/Report.swift
  o-fish-ios/ViewModel/Report/AnnotatedNoteViewModel.swift
  o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
  o-fish-ios/ViewModel/Report/BoatViewModel.swift
  o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
  o-fish-ios/ViewModel/Report/InspectionViewModel.swift
  o-fish-ios/ViewModel/Report/ReportViewModel.swift
  o-fish-ios/ViewModel/Report/SummaryViewModel.swift
  o-fish-ios/ViewModel/User/NameViewModel.swift
  o-fish-ios/ViewModel/User/UserViewModel.swift
Labels: Architecture

#304 Cancel Boarding Modal change
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Design/Color+Design.swift
  o-fish-ios/SceneDelegate.swift
  o-fish-ios/Views/Components/ActionSheetItem.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: days: 2

#313 Draft boardings on home page
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Views/DraftBoardings/DraftBoardingLoadedStateView.swift
  o-fish-ios/Views/DraftBoardings/DraftBoardingsView.swift
  o-fish-ios/Views/DraftBoardings/EmptyDraftView.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/LoadingVesselRecordView.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
Labels: days: 3

#322 Not at sea and drafts
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios/Views/Components/CallToActionButton.swift
  o-fish-ios/Views/Components/SegmentedField.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
  o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift
  o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
  o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
  o-fish-ios/Views/ReportFlow/CrewMemberShortView.swift
  o-fish-ios/Views/ReportFlow/Risk/TrafficLightButton.swift
Labels: days: 1

#279 Position moves when zooming
  o-fish-ios/Views/Components/Maps/MapDisplayView.swift
  o-fish-ios/Views/ReportDetails/Map/LocationDisplayView.swift
Labels: bug

#328 No photos or notes
  o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
  o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
  o-fish-ios/Views/ReportDetails/RiskSummaryView.swift
  o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Labels: bug
