Repository WildAid/o-fish-ios, pull requests merged in 2020-07, with the labels that each got.

#104 Latitude and longitude precision
  o-fish-ios/Design/Color+Design.swift
  o-fish-ios/Helpers/Double+LocationDegrees.swift
  o-fish-ios/Views/Components/Icons/AddAttachmentIconView.swift
  o-fish-ios/Views/Components/Icons/EditIconView.swift
  o-fish-ios/Views/Components/Icons/ExclamationIconView.swift
  o-fish-ios/Views/Components/MinusIconView.swift
  o-fish-ios/Views/Components/Pictures/PhotoThumbNail.swift
Labels: enhancement

#66 Pre-boarding search results
  o-fish-ios/Views/PreboardingFlow/PreboardingView/LoadedStateView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
Labels: enhancement

#76 Logout Modal
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Design/Color+Design.swift
  o-fish-ios/Views/Components/ActionSheetButton.swift
  o-fish-ios/Views/Components/AddAttachmentsButton.swift
  o-fish-ios/Views/Components/AddAttachmentsModalView.swift
  o-fish-ios/Views/Components/LogoutModalView.swift
  o-fish-ios/Views/Components/Popover/PopoverManager.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
Labels: enhancement

#111 Edit date and time
  o-fish-ios/Views/Components/DatePickerWithButton.swift
  o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
  o-fish-ios/Views/ReportFlow/BasicInfo/DateTimeView.swift
Labels: enhancement

#110 Violation issue to CrewMember screen
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
  o-fish-ios/Views/Components/AddAttachmentsModalView.swift
  o-fish-ios/Views/Components/Icons/IconLabel.swift
  o-fish-ios/Views/Components/RemovableViewModifier.swift
  o-fish-ios/Views/Components/SegmentedField.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchOnBoardView.swift
  o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseCrewMemberView.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewMemberView.swift
  o-fish-ios/Views/ReportFlow/CrewMemberShortView.swift
  o-fish-ios/Views/ReportFlow/Notes/NoteView.swift
  o-fish-ios/Views/ReportFlow/Vessel/EMSView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationCreateCrewMemberView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationView.swift
Labels: enhancement

#114 Next button
  o-fish-ios/Views/Components/CallToActionButton.swift
Labels: enhancement

#117 Use correct ID when setting Photo.referencingReportID
  o-fish-ios/Views/Components/AddAttachmentsButton.swift
  o-fish-ios/Views/ReportFlow/Activity/ActivityItemView.swift
  o-fish-ios/Views/ReportFlow/Activity/ActivityView.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchOnBoardView.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchView.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewMemberInputView.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewMemberView.swift
  o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
  o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
  o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
  o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
  o-fish-ios/Views/ReportFlow/Vessel/DeliveryView.swift
  o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
  o-fish-ios/Views/ReportFlow/Vessel/EMSView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselInformationInputView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselInformationView.swift
  o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationCreateCrewMemberView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationSeizureInputView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationsView.swift
Labels: bug

#115 Container template changes
  o-fish-ios/Views/Components/LabeledText.swift
  o-fish-ios/Views/PatrolBoat/DutyReportsView.swift
  o-fish-ios/Views/ReportDetails/CatchItemView.swift
  o-fish-ios/Views/ReportDetails/CrewItemView.swift
  o-fish-ios/Views/ReportDetails/EMSSummaryView.swift
  o-fish-ios/Views/ReportDetails/LastDeliverySummaryView.swift
  o-fish-ios/Views/ReportDetails/VesselSummaryView.swift
  o-fish-ios/Views/ReportDetails/ViolationStaticItemView.swift
Labels: enhancement

#113 Board vessel button
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Views/Components/BoardVesselButton.swift
  o-fish-ios/Views/Components/SectionButton.swift
  o-fish-ios/Views/PatrolBoat/DutyReportsView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
  o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
  o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
  o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
  o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
Labels: enhancement

#118 Prompt are you still on duty
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/AppDelegate.swift
  o-fish-ios/Helpers/Constants.swift
  o-fish-ios/Helpers/NotificationManager.swift
  o-fish-ios/SceneDelegate.swift
  o-fish-ios/ViewModel/User/SampleUserViewModel.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingLoadedStateView.swift
Labels: enhancement

#122 Fix build warnings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/ViewModel/Report/ReportViewModel.swift
  o-fish-ios/Views/Components/PageView/PageViewController.swift
  o-fish-ios/Views/Components/StartStopDatePicker.swift
  o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
Labels: enhancement

#125 Change the bundle id
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Info.plist
Labels: bug

#126 Add sample privacy policy
  privacy-sample.md
Labels: documentation

#142 Getting 4-hour on-duty notifications even when off-duty
  o-fish-ios/Helpers/NotificationManager.swift
  o-fish-ios/SceneDelegate.swift
  o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
Labels: bug

#144 Violation title shouldn't be broken into 2 rows
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios/ViewModel/Report/OffenceViewModel.swift
  o-fish-ios/ViewModel/Report/ViolationViewModel.swift
  o-fish-ios/Views/Components/Picker/Violation/ViolationPickerDataView.swift
  o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
Labels: bug

#145 Cope with the Location in the Realm Report Object being an array
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Model/Report/Location.swift
  o-fish-ios/Model/Report/Report.swift
  o-fish-ios/ViewModel/Report/LocationViewModel.swift
  o-fish-ios/ViewModel/Report/ReportViewModel.swift
Labels: enhancement

#147 Allow photo library to be used for attachments
  o-fish-ios/Views/Components/Pictures/PhotoCaptureController.swift
Labels: bug

#149 Banner image pixelated
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Helpers/ImageLoading/VesselAsyncImage.swift
  o-fish-ios/Views/Components/PageView/PageViewController.swift
  o-fish-ios/Views/Components/Pictures/PhotoVesselView.swift
  o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
Labels: bug

#154 FaceID Auth
  Localization/es-419.lproj/Localizable.strings
  Localization/fr.lproj/Localizable.strings
  Localization/uk.lproj/Localizable.strings
  o-fish-ios.xcodeproj/project.pbxproj
  o-fish-ios/Helpers/KeychainWrapper.swift
  o-fish-ios/Info.plist
  o-fish-ios/Model/Settings.swift
  o-fish-ios/Views/LoginView.swift
Labels: enhancement

#168 Incorrect crew member count
  o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
Labels: bug

#169 Previous 5 boardings not sorted properly
  o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
Labels: bug
